version: '3'
services:
  kafka:
    image: my-kafka:2.8.0
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - application-a
      - application-b

  application-a:
    image: my-application-a:1.0.0
    depends_on:
      - kafka

  application-b:
    image: my-application-b:1.0.0
    depends_on:
      - kafka
